# Generated by Django 5.2.4 on 2025-07-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Naira (₦)', max_digits=10),
        ),
    ]
